# Generated by Django 4.1.6 on 2023-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], max_length=100),
        ),
    ]
